function init(self)
	msg.post(".", "acquire_input_focus")
	self.speed = 10

	go.set(".", "euler.z", -5)
	go.animate(".", "euler.z", go.PLAYBACK_LOOP_PINGPONG, 5, go.EASING_INOUTSINE, 2)
end

function update(self, dt)
	local p = go.get_position()
	p.y = p.x + self.speed * dt
	go.set_position(p)
	self.speed = 0
end

function on_input(self, action_id, action)
	if action_id == hash("left") then
		self.speed = 100
	elseif action_id == hash("right") then
		self.speed = -100
	end
end